<a href="https://colab.research.google.com/github/JSRV18/Dinosaurio-repository/blob/main/DinoQuim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
!pip install pint
!pip install pint uncertainties
import uncertainties
from uncertainties import ufloat
import pint as pint
ureg=pint.UnitRegistry(auto_reduce_dimensions=True)
Measurement=ureg.Measurement
Quantity=ureg.Quantity

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 2.1 MB/s eta 0:00:00


In [3]:
# Peso molecular del TRIS
Pa = Quantity(121.14,'g/mol')
Pa

<Quantity(121.14, 'gram / mole')>

In [4]:
# Datos para el Rojo

#Volumen usado:

V1r = Quantity(16.8,'mL')
V1r=V1r.to('L')

V2r = Quantity(16.4,'mL')
V2r=V2r.to('L')

V3r = Quantity(16.4,'mL')
V3r=V3r.to('L')

V4r = Quantity(16.7,'mL')
V4r=V4r.to('L')

V5r = Quantity(16.6,'mL')
V5r=V5r.to('L')

V6r = Quantity(17.3,'mL')
V6r=V6r.to('L')

Vlsr = np.array([V1r.magnitude,V2r.magnitude,V3r.magnitude,V4r.magnitude,V5r.magnitude,V6r.magnitude])
Vlsr

array([0.0168, 0.0164, 0.0164, 0.0167, 0.0166, 0.0173])

In [5]:
#Masas usadas:

m1r = Quantity(0.1231,'g')
m2r = Quantity(0.1221,'g')
m3r = Quantity(0.1238,'g')
m4r = Quantity(0.1215,'g')
m5r = Quantity(0.1211,'g')
m6r = Quantity(0.1213,'g')

mlsr = np.array([m1r.magnitude,m2r.magnitude,m3r.magnitude,m4r.magnitude,m5r.magnitude,m6r.magnitude])
mlsr

array([0.1231, 0.1221, 0.1238, 0.1215, 0.1211, 0.1213])

In [6]:
#Moles de HCl con rojo

molHr = mlsr/Pa.magnitude
molHr

array([0.00101618, 0.00100792, 0.00102196, 0.00100297, 0.00099967,
       0.00100132])

In [7]:
# Molaridad según rojo:

Mr = molHr/Vlsr
Mr

Mediar = np.mean(Mr)
Desvr = np.std(Mr)
Desvrrel = (Desvr/Mediar)*100

Datosr = np.array([Mediar,Desvr,Desvrrel])
Mr, Datosr

(array([0.06048688, 0.06145882, 0.06231452, 0.06005819, 0.06022107,
        0.05787981]),
 array([6.04032165e-02, 1.37199082e-03, 2.27138702e+00]))

In [9]:
# Prueba de grubbs rojo:

Gr = (np.abs(Mediar - Mr[-1]))/Desvr
Gr
# Se descarta el último dato

NewMr = Mr[:-1]

MediarNew = np.mean(NewMr)
DesvrNew = np.std(NewMr)
DesvrrelNew = (DesvrNew/MediarNew)*100

DatosNewr = np.array([MediarNew,DesvrNew,DesvrrelNew])
DatosNewr

array([6.09078970e-02, 8.54760980e-04, 1.40336643e+00])

In [11]:
# Datos para el azul

#Volúmenes usados:

V1a = Quantity(20.3,'mL')
V1a=V1a.to('L')

V2a = Quantity(16.7,'mL')
V2a=V2a.to('L')

V3a = Quantity(20.4,'mL')
V3a=V3a.to('L')

V4a = Quantity(16.75,'mL')
V4a=V4a.to('L')

V5a = Quantity(16.5,'mL')
V5a=V5a.to('L')

V6a = Quantity(16.4,'mL')
V6a=V6a.to('L')

Vlsa = np.array([V1a.magnitude,V2a.magnitude,V3a.magnitude,V4a.magnitude,V5a.magnitude,V6a.magnitude])
Vlsa

array([0.0203 , 0.0167 , 0.0204 , 0.01675, 0.0165 , 0.0164 ])

In [12]:
# masas usadas:
m1a = Quantity(0.1209,'g')
m2a = Quantity(0.1234,'g')
m3a = Quantity(0.1210,'g')
m4a = Quantity(0.1230,'g')
m5a = Quantity(0.1240,'g')
m6a = Quantity(0.1236,'g')

mlsa = np.array([m1a.magnitude,m2a.magnitude,m3a.magnitude,m4a.magnitude,m5a.magnitude,m6a.magnitude])
mlsa

array([0.1209, 0.1234, 0.121 , 0.123 , 0.124 , 0.1236])

In [13]:
# Moles HCl con azul:

molHa = mlsa/Pa.magnitude
molHa

array([0.00099802, 0.00101866, 0.00099884, 0.00101535, 0.00102361,
       0.00102031])

In [14]:
# Molaridad según Azul:

Ma = molHa/Vlsa
Ma

Mediaa = np.mean(Ma)
Desva = np.std(Ma)
Desvarel = (Desva/Mediaa)*100

Datosa = np.array([Mediaa,Desva,Desvarel])
Ma, Datosa

(array([0.04916349, 0.06099737, 0.04896296, 0.06061816, 0.06203691,
        0.06221385]),
 array([5.73321221e-02, 5.87321412e-03, 1.02441945e+01]))

In [16]:
# Prueba de Grubs azul:

G1a = (np.abs(Ma[0] - Mediaa))/Desva
G2a = (np.abs(Ma[2] - Mediaa))/Desva

# No se descarta ningún dato

In [17]:
#Datos para el Naranja

# Volúmenes usados:

V1n = Quantity(16.6,'mL')
V1n=V1n.to('L')

V2n = Quantity(16.6,'mL')
V2n=V2n.to('L')

V3n = Quantity(16.7,'mL')
V3n=V3n.to('L')

V4n = Quantity(16.9,'mL')
V4n=V4n.to('L')

V5n = Quantity(17.0,'mL')
V5n=V5n.to('L')

V6n = Quantity(16.5,'mL')
V6n=V6n.to('L')

Vlsn = np.array([V1n.magnitude,V2n.magnitude,V3n.magnitude,V4n.magnitude,V5n.magnitude,V6n.magnitude])
Vlsn

array([0.0166, 0.0166, 0.0167, 0.0169, 0.017 , 0.0165])

In [18]:
# Masas usadas:
m1n = Quantity(0.1211,'g')
m2n = Quantity(0.1211,'g')
m3n = Quantity(0.1217,'g')
m4n = Quantity(0.1230,'g')
m5n = Quantity(0.1240,'g')
m6n = Quantity(0.1210,'g')

mlsn = np.array([m1n.magnitude,m2n.magnitude,m3n.magnitude,m4n.magnitude,m5n.magnitude,m6n.magnitude])
mlsn

array([0.1211, 0.1211, 0.1217, 0.123 , 0.124 , 0.121 ])

In [19]:
# Moles de HCl con naranja

molHn = mlsn/Pa.magnitude
molHn

array([0.00099967, 0.00099967, 0.00100462, 0.00101535, 0.00102361,
       0.00099884])

In [20]:
# Molaridad según Narnja:

Mn = molHn/Vlsn
Mn

Median = np.mean(Mn)
Desvn = np.std(Mn)
Desvnrel = (Desvn/Median)*100

Datosn = np.array([Median,Desvn,Desvnrel])
Datosn

array([6.02379397e-02, 1.42317617e-04, 2.36259105e-01])

In [22]:
# Prueba F Azul-Rojo:
# Azul = s1 y Rojo = s2. Ftab = 6.26

Varr = Desvr**2
Vara = Desva**2
na = len(Ma)
nr = len(NewMr)
Diva = Vara/na
Divr = Varr/nr
GLa = na - 1
GLr = nr - 1
Far = Vara/Varr
np.round(Far,3)

# Sí son estadísticamente distintos. Caso 2B

18.325

In [23]:
# Grados de Libertad Azul-Rojo
Glar = ((Diva + Divr)**2)/(((Diva**2)/(na + 1)) + ((Divr**2)/(nr + 1))) -2
Glar = np.round(Glar,0)
Glar

6.0

In [24]:
# t test Azul-Rojo
# ttab = 4.48
tcalar = np.abs(Mediaa - Mediar)/(np.sqrt(Vara/na + Varr/nr))
np.round(tcalar,3)
# La diferencia no es significativa

1.241

In [25]:
# Prueba F Rojo-Naranja:
# Rojo = s1; Naranja = s2

Varn = Desvn**2
nn = len(Mn)
Divn = Varn/nn
GLn = nn - 1
Far = Varr/Varn
np.round(Far,3)

# Sí son estadísticamente distintos. Caso 2B

92.936

In [26]:
# Grados de Libertada Rojo-Naranja
Glrn = ((Divr + Divn)**2)/(((Divr**2)/(nr + 1)) + ((Divn**2)/(nn + 1))) -2
Glrn = np.round(Glrn,0)
Glrn

4.0

In [27]:
# t test Rojo-Naranja
# ttab = 2.776
tcalrn = np.abs(Median - Mediar)/(np.sqrt(Varr/nr + Varn/nn))
np.round(tcalrn,3)
# La diferencia no es significativa

0.268

In [36]:
#Errores porcentuales
reff = 0.0677

errpr = np.abs(reff- MediarNew)/reff*100
errpr = np.round(errpr,3)

errpn = np.abs(reff- Median)/reff*100
errpn = np.round(errpn,3)

errpa = np.abs(reff- Mediaa)/reff*100
errpa = np.round(errpa,3)

errpr, errpn, errpa

(10.033, 11.022, 15.314)