<a href="https://colab.research.google.com/github/JSRV18/Dinosaurio-repository/blob/main/Parcial2Dinosaurio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
# Parcial

#Punto 24 (Tierra plana)

# (a)
import numpy as np
xi,wi = np.polynomial.legendre.leggauss(50)

In [166]:
# (b)
k= -1.9429303960
def dg(ϕ,r,x,y,z):
  return (k*z*r)/((x**2 + y**2 + z**2 -2*r*x*np.cos(ϕ) -2*r*y*np.sin(ϕ)))**(3/2)

In [167]:
# (c)
a=0
b=2*np.pi
c=0
R=1

def g(x,y,z):
  sum = 0
  for i in range (len(xi)):
    for j in range (len(xi)):
      tϕ = 0.5*((b-a)*xi[i] + b + a)
      tr = 0.5*((R-c)*xi[j] + R + c)
      sum += 0.25*(b-a)*(R-c)*np.sum(np.sum(wi[i]*wi[j]*dg(tϕ,tr,x,y,z)))

  return sum

In [168]:
# (d)
g(0.,0.,0.2)

-152.5973964627477

In [150]:
# (e)
def polares(r,θ):
  x=r*np.cos(θ)
  y=r*np.sin(θ)
  return x,y

In [151]:
u=np.linspace(0,2*np.pi,10)
u

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [162]:
polares(0.125,u)

(array([ 0.125     ,  0.09575556,  0.02170602, -0.0625    , -0.11746158,
        -0.11746158, -0.0625    ,  0.02170602,  0.09575556,  0.125     ]),
 array([ 0.00000000e+00,  8.03484512e-02,  1.23100969e-01,  1.08253175e-01,
         4.27525179e-02, -4.27525179e-02, -1.08253175e-01, -1.23100969e-01,
        -8.03484512e-02, -3.06161700e-17]))

In [165]:
g(0.09575556,8.03484512e-02,0.2)

-447.141443640477

[-98.13646003744714, -98.13646003744714]

In [303]:
# Punto 27
import time

G8=(lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**0 + w1*x1**0 + w2*x2**0 + w3*x3**0 -2, \
    lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**1 + w1*x1**1 + w2*x2**1 + w3*x3**1, \
    lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**2 + w1*x1**2 + w2*x2**2 + w3*x3**2 -2/3, \
    lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**3 + w1*x1**3 + w2*x2**3 + w3*x3**3, \
    lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**4 + w1*x1**4 + w2*x2**4 + w3*x3**4 -2/5, \
    lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**5 + w1*x1**5 + w2*x2**5 + w3*x3**5, \
    lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**6 + w1*x1**6 + w2*x2**6 + w3*x3**6 -2/7,\
    lambda w0,w1,w2,w3,x0,x1,x2,x3: w0*x0**7 + w1*x1**7 + w2*x2**7 + w3*x3**7,)

def GetF(f,r):

  dim = len(f)
  v = np.zeros(dim)

  for i in range(dim):
    v[i] = f[i](r[0],r[1],r[2],r[3],r[4],r[5],r[6],r[7])

  return v

def GetJacobian8(f, r, h=1e-3):
    dim = len(r)
    J = np.zeros((len(f), dim))

    for i in range(len(f)):
        for j in range(dim):
            dr = np.zeros(dim)
            dr[j] = h

            J[i, j] = (f[i](r[0]+dr[0],r[1]+dr[1],r[2]+dr[2],r[3]+dr[3],r[4]+dr[4],r[5]+dr[5],r[6]+dr[6],r[7]+dr[7]) - \
                       f[i](r[0]-dr[0],r[1]-dr[1],r[2]-dr[2],r[3]-dr[3],r[4]-dr[4],r[5]-dr[5],r[6]-dr[6],r[7]-dr[7])) / (2*h)
    return J.T

def GetMetric8(f,r):
  v=GetF(f,r)
  return 0.5*np.linalg.norm(v)**2

def descenso(f, r, lr, epoch, err):


  r=r.astype(np.float64)

  d=1
  it=0
  Vector = np.array([])
  R_vector = np.array(r)

  while d>err and it<epoch:

    Current = GetMetric8(f,r)
    J = GetJacobian8(f,r)
    Gvector = GetF(f,r)

    r-= lr*np.dot(J,Gvector)
    R_vector = np.vstack((R_vector,r))
    New=GetMetric8(f,r)
    Vector=np.append(Vector,New)
    d=abs(Current-New)/New

    if it%500==0:
      time.sleep(0.01)

    it+=1

  return r,it

In [308]:
sol=descenso(G8,np.random.uniform(-1.,1.,size=8),0.01,100000,1e-4)
sol

(array([ 0.53923137,  0.05350543,  0.5020755 ,  0.90436219, -0.79058237,
         0.24473436,  0.8031961 ,  0.01229379]),
 4394)

In [310]:
f=lambda x: np.cos(x)
I = np.sum(sol[0][:4] * f(sol[0][4:]))
I

1.684163691522904